version: '3'
services:
  backend:
    image: llama-nuts-and-bolts/backend:win-amd64
    build:
      context: . # Dockerfile location
      args:
        # See for available variants: https://hub.docker.com/_/golang?tab=tags
        - VARIANT:1.21.5-windowsservercore
    # See: https://code.visualstudio.com/docs/remote/create-dev-container#_set-up-a-folder-to-run-in-a-container
    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined
    volumes:
      # Mount the root folder that contains .git
      - "../..:c:/workspace:cached"
